In [2]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma",
             "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "Age": [25, 30, 28, 35, 24, 40, 29, 32, 27, 38],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [50000, 60000, 55000, 75000, 48000,
               90000, 70000, 65000, 52000, 80000],
    "Experience": [2, 5, 3, 10, 1, 15, 7, 6, 4, 12],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Chennai", "Bangalore", "Hyderabad", "Chennai",
             "Bangalore", "Hyderabad"]
}

df = pd.DataFrame(data)

print(df)

   Employee_ID     Name  Age Department  Salary  Experience       City
0          101    Alice   25         IT   50000           2  Hyderabad
1          102      Bob   30         HR   60000           5    Chennai
2          103  Charlie   28         IT   55000           3  Bangalore
3          104    David   35    Finance   75000          10  Hyderabad
4          105     Emma   24         HR   48000           1    Chennai
5          106    Frank   40         IT   90000          15  Bangalore
6          107    Grace   29    Finance   70000           7  Hyderabad
7          108    Henry   32         IT   65000           6    Chennai
8          109      Ivy   27         HR   52000           4  Bangalore
9          110     Jack   38    Finance   80000          12  Hyderabad

In [5]:
#Display the first 5 rows.
df.head()

   Employee_ID     Name  Age Department  Salary  Experience       City
0          101    Alice   25         IT   50000           2  Hyderabad
1          102      Bob   30         HR   60000           5    Chennai
2          103  Charlie   28         IT   55000           3  Bangalore
3          104    David   35    Finance   75000          10  Hyderabad
4          105     Emma   24         HR   48000           1    Chennai

In [6]:
#Display the last 3 rows.
df.tail(3)

   Employee_ID   Name  Age Department  Salary  Experience       City
7          108  Henry   32         IT   65000           6    Chennai
8          109    Ivy   27         HR   52000           4  Bangalore
9          110   Jack   38    Finance   80000          12  Hyderabad

In [4]:
#Find the number of rows and columns.
df.shape

(10, 7)

In [ ]:
#Display all column names.
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Experience',
       'City'],
      dtype='str')

In [6]:
#Display the data types of each column
df.dtypes

Employee_ID    int64
Name             str
Age            int64
Department       str
Salary         int64
Experience     int64
City             str
dtype: object

In [7]:
#Display only the Name column.
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
5      Frank
6      Grace
7      Henry
8        Ivy
9       Jack
Name: Name, dtype: str

In [8]:
#Display Name, Department, and Salary.
df[['Name', 'Department', 'Salary']]

      Name Department  Salary
0    Alice         IT   50000
1      Bob         HR   60000
2  Charlie         IT   55000
3    David    Finance   75000
4     Emma         HR   48000
5    Frank         IT   90000
6    Grace    Finance   70000
7    Henry         IT   65000
8      Ivy         HR   52000
9     Jack    Finance   80000

In [12]:
#Find the employee with Employee_ID = 105.
df[df['Employee_ID'] == 105]

   Employee_ID  Name  Age Department  Salary  Experience     City
4          105  Emma   24         HR   48000           1  Chennai

In [17]:
#Display employees whose age is greater than 30.
df[df['Age'] > 30]

   Employee_ID   Name  Age Department  Salary  Experience       City
3          104  David   35    Finance   75000          10  Hyderabad
5          106  Frank   40         IT   90000          15  Bangalore
7          108  Henry   32         IT   65000           6    Chennai
9          110   Jack   38    Finance   80000          12  Hyderabad

In [18]:
#Display employees whose salary is greater than 60,000.
df[df['Salary'] > 60000]

   Employee_ID   Name  Age Department  Salary  Experience       City
3          104  David   35    Finance   75000          10  Hyderabad
5          106  Frank   40         IT   90000          15  Bangalore
6          107  Grace   29    Finance   70000           7  Hyderabad
7          108  Henry   32         IT   65000           6    Chennai
9          110   Jack   38    Finance   80000          12  Hyderabad

In [23]:
#Find the average salary.
#df.groupby('Salary').agg({'Salary':'mean'})
df['Salary'].mean()

np.float64(64500.0)

In [24]:
#Find the maximum salary.
df['Salary'].max()

np.int64(90000)

In [25]:
#Find the minimum salary.
df['Salary'].min()

np.int64(48000)

In [26]:
#Find the employee who has the highest salary.
df.loc[df["Salary"].idxmax()]

Employee_ID          106
Name               Frank
Age                   40
Department            IT
Salary             90000
Experience            15
City           Bangalore
Name: 5, dtype: object

In [27]:
#Find the employee who has the lowest salary.
df.loc[df["Salary"].idxmin()]

Employee_ID        105
Name              Emma
Age                 24
Department          HR
Salary           48000
Experience           1
City           Chennai
Name: 4, dtype: object

In [29]:
#find the average age of employees.
df['Age'].mean()

np.float64(30.8)

In [31]:
#Find the average salary for each department.
df.groupby('Department').agg({'Salary':'mean'})

                  Salary
Department
Finance     75000.000000
HR          53333.333333
IT          65000.000000

In [32]:
#Find the maximum salary in each department.
df.groupby('Department').agg({'Salary':'max'})

            Salary
Department
Finance      80000
HR           60000
IT           90000

In [36]:
#Count how many employees are in each department.
df.groupby('Department').size()

Department
Finance    3
HR         3
IT         4
dtype: int64

In [37]:
#Count how many employees are from each city.
df.groupby('City').size()

City
Bangalore    3
Chennai      3
Hyderabad    4
dtype: int64

In [38]:
df

   Employee_ID     Name  Age Department  Salary  Experience       City
0          101    Alice   25         IT   50000           2  Hyderabad
1          102      Bob   30         HR   60000           5    Chennai
2          103  Charlie   28         IT   55000           3  Bangalore
3          104    David   35    Finance   75000          10  Hyderabad
4          105     Emma   24         HR   48000           1    Chennai
5          106    Frank   40         IT   90000          15  Bangalore
6          107    Grace   29    Finance   70000           7  Hyderabad
7          108    Henry   32         IT   65000           6    Chennai
8          109      Ivy   27         HR   52000           4  Bangalore
9          110     Jack   38    Finance   80000          12  Hyderabad

In [39]:
#Find employees who work in the IT department.
df[df['Department'] == 'IT']

   Employee_ID     Name  Age Department  Salary  Experience       City
0          101    Alice   25         IT   50000           2  Hyderabad
2          103  Charlie   28         IT   55000           3  Bangalore
5          106    Frank   40         IT   90000          15  Bangalore
7          108    Henry   32         IT   65000           6    Chennai

In [46]:
#Find employees from Hyderabad with salary greater than 60,000.
df[(df['City'] == 'Hyderabad') & (df['Salary'] > 60000)]

   Employee_ID   Name  Age Department  Salary  Experience       City
3          104  David   35    Finance   75000          10  Hyderabad
6          107  Grace   29    Finance   70000           7  Hyderabad
9          110   Jack   38    Finance   80000          12  Hyderabad

In [48]:
#Sort employees by salary in ascending order.
df['Salary'].sort_values(ascending=True)

4    48000
0    50000
8    52000
2    55000
1    60000
7    65000
6    70000
3    75000
9    80000
5    90000
Name: Salary, dtype: int64

In [50]:
#Sort employees by salary in descending order.
df['Salary'].sort_values(ascending=False)

5    90000
9    80000
3    75000
6    70000
7    65000
1    60000
2    55000
8    52000
0    50000
4    48000
Name: Salary, dtype: int64

In [54]:
#Sort employees by Experience from highest to lowest
df.sort_values('Experience', ascending=False)

   Employee_ID     Name  Age Department  Salary  Experience       City
5          106    Frank   40         IT   90000          15  Bangalore
9          110     Jack   38    Finance   80000          12  Hyderabad
3          104    David   35    Finance   75000          10  Hyderabad
6          107    Grace   29    Finance   70000           7  Hyderabad
7          108    Henry   32         IT   65000           6    Chennai
1          102      Bob   30         HR   60000           5    Chennai
8          109      Ivy   27         HR   52000           4  Bangalore
2          103  Charlie   28         IT   55000           3  Bangalore
0          101    Alice   25         IT   50000           2  Hyderabad
4          105     Emma   24         HR   48000           1    Chennai

In [57]:
#Find the average salary by department and city.
df.groupby(['Department', 'City']).agg({'Salary':'mean'})

                       Salary
Department City
Finance    Hyderabad  75000.0
HR         Bangalore  52000.0
           Chennai    54000.0
IT         Bangalore  72500.0
           Chennai    65000.0
           Hyderabad  50000.0

In [14]:
#Add a new column called Bonus, where bonus = 10% of salary.
df['Bonus'] = df["Salary"] * 0.1

In [62]:
df

   Employee_ID     Name  Age Department  Salary  Experience       City   Bonus
0          101    Alice   25         IT   50000           2  Hyderabad  5000.0
1          102      Bob   30         HR   60000           5    Chennai  6000.0
2          103  Charlie   28         IT   55000           3  Bangalore  5500.0
3          104    David   35    Finance   75000          10  Hyderabad  7500.0
4          105     Emma   24         HR   48000           1    Chennai  4800.0
5          106    Frank   40         IT   90000          15  Bangalore  9000.0
6          107    Grace   29    Finance   70000           7  Hyderabad  7000.0
7          108    Henry   32         IT   65000           6    Chennai  6500.0
8          109      Ivy   27         HR   52000           4  Bangalore  5200.0
9          110     Jack   38    Finance   80000          12  Hyderabad  8000.0

In [15]:
#Add a column Total_Salary = Salary + Bonus.
df['Total'] = df['Salary'] + df['Bonus']
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Bonus,Total
0,101,Alice,25,IT,50000,2,Hyderabad,5000.0,55000.0
1,102,Bob,30,HR,60000,5,Chennai,6000.0,66000.0
2,103,Charlie,28,IT,55000,3,Bangalore,5500.0,60500.0
3,104,David,35,Finance,75000,10,Hyderabad,7500.0,82500.0
4,105,Emma,24,HR,48000,1,Chennai,4800.0,52800.0
5,106,Frank,40,IT,90000,15,Bangalore,9000.0,99000.0
6,107,Grace,29,Finance,70000,7,Hyderabad,7000.0,77000.0
7,108,Henry,32,IT,65000,6,Chennai,6500.0,71500.0
8,109,Ivy,27,HR,52000,4,Bangalore,5200.0,57200.0
9,110,Jack,38,Finance,80000,12,Hyderabad,8000.0,88000.0

In [71]:
#Increase everyone's salary by 5%.
df['Salary'] = df['Salary'] * 1.05

In [72]:
df

   Employee_ID     Name  Age Department   Salary  Experience       City
0          101    Alice   25         IT  52500.0           2  Hyderabad
1          102      Bob   30         HR  63000.0           5    Chennai
2          103  Charlie   28         IT  57750.0           3  Bangalore
3          104    David   35    Finance  78750.0          10  Hyderabad
4          105     Emma   24         HR  50400.0           1    Chennai
5          106    Frank   40         IT  94500.0          15  Bangalore
6          107    Grace   29    Finance  73500.0           7  Hyderabad
7          108    Henry   32         IT  68250.0           6    Chennai
8          109      Ivy   27         HR  54600.0           4  Bangalore
9          110     Jack   38    Finance  84000.0          12  Hyderabad

In [76]:
#Find the top 3 highest-paid employees.
df.sort_values('Salary', ascending=False).head(3)

   Employee_ID   Name  Age Department   Salary  Experience       City
5          106  Frank   40         IT  94500.0          15  Bangalore
9          110   Jack   38    Finance  84000.0          12  Hyderabad
3          104  David   35    Finance  78750.0          10  Hyderabad

In [79]:
#Find the top 2 highest-paid employees from each department.
df.sort_values(by=["Department", "Salary"]).groupby('Department').head(1)

   Employee_ID   Name  Age Department   Salary  Experience       City
6          107  Grace   29    Finance  73500.0           7  Hyderabad
4          105   Emma   24         HR  50400.0           1    Chennai
0          101  Alice   25         IT  52500.0           2  Hyderabad

In [5]:
#find employees whose salary is above the overall average salary.
df[df['Salary'] > df['Salary'].mean()]

   Employee_ID   Name  Age Department  Salary  Experience       City
3          104  David   35    Finance   75000          10  Hyderabad
5          106  Frank   40         IT   90000          15  Bangalore
6          107  Grace   29    Finance   70000           7  Hyderabad
7          108  Henry   32         IT   65000           6    Chennai
9          110   Jack   38    Finance   80000          12  Hyderabad

In [8]:
#Find the youngest employee in each department.
df.loc[df.groupby('Department')['Age'].idxmin()]

   Employee_ID   Name  Age Department  Salary  Experience       City
6          107  Grace   29    Finance   70000           7  Hyderabad
4          105   Emma   24         HR   48000           1    Chennai
0          101  Alice   25         IT   50000           2  Hyderabad

In [9]:
df.loc[df.groupby('Department')['Salary'].idxmax()]

   Employee_ID   Name  Age Department  Salary  Experience       City
9          110   Jack   38    Finance   80000          12  Hyderabad
1          102    Bob   30         HR   60000           5    Chennai
5          106  Frank   40         IT   90000          15  Bangalore

In [17]:
#Find the most experienced employee in each department.
df.loc[df.groupby('Department')['Experience'].idxmax()]

,Employee_ID,Name,Age,Department,Salary,Experience,City,Bonus,Total
9,110,Jack,38,Finance,80000,12,Hyderabad,8000.0,88000.0
1,102,Bob,30,HR,60000,5,Chennai,6000.0,66000.0
5,106,Frank,40,IT,90000,15,Bangalore,9000.0,99000.0

In [19]:
#Find the total salary paid by each department.
df.groupby('Department').agg({'Total': 'sum'})

               Total
Department
Finance     247500.0
HR          176000.0
IT          286000.0

In [21]:
#Find the department having the largest number of employees.
df['Department'].value_counts().idxmax()

'IT'